const Joi = require('joi')

const GHN_ORDER_SCHEMA = {
  token: Joi.string().required(),
  shop_id: Joi.string().required(),
  to_name: Joi.string().required(),
  from_name: Joi.string(),
  from_phone: Joi.string(),
  from_ward_name: Joi.string(),
  from_district_name: Joi.string(),
  from_province_name: Joi.string(),
  to_phone: Joi.string().required(),
  to_address: Joi.string().required(),
  to_ward_code: Joi.string().required(),
  to_district_id: Joi.number().required(),
  return_phone: Joi.string(),
  return_address: Joi.string(),
  return_district_id: Joi.number(),
  return_ward_code: Joi.string(),
  client_order_code: Joi.string().default(null),
  cod_amount: Joi.number().max(50000000).default(0),
  content: Joi.string(),
  weight: Joi.number().required().max(50000),
  length: Joi.number().required().max(200),
  width: Joi.number().required().max(200),
  height: Joi.number().required().max(200),
  pick_station_id: Joi.number(),
  insurance_value: Joi.number().max(5000000).default(0),
  coupon: Joi.string(),
  service_type_id: Joi.number().required().default(2),
  payment_type_id: Joi.number().required().default(2),
  note: Joi.string(),
  required_note: Joi.string().required().default('KHONGCHOXEMHANG'),
  Items: Joi.array().items({
    name: Joi.string().required(),
    code: Joi.string(),
    quantity: Joi.number().required(),
    price: Joi.number().required(),
    length: Joi.number().required(),
    weight: Joi.number().required(),
    width: Joi.number().required(),
    height: Joi.number().required()
  })
}